spring:
  datasource:
    url: jdbc:mysql://localhost:3306/groovy
    driver-class-name: com.mysql.jdbc.Driver
    username: user
    password: Password01
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect


